### ISSUE TITLE
`plot` and `predict` methods error from `example.R`

### ISSUE THREAD

**Issue by dill** [r-glennie/CTMCdive#1]
Calling these functions yields:

```
Error in r_dive[i] <- Ssurf[floor(mod$dat$dive[i]/dt)] : 
  replacement has length zero
```

**Comment by dill** [comment]
dae50af proposes a fix to this, does this seem right @r-glennie?

issue was at lines [326](https://github.com/r-glennie/CTMCdive/commit/dae50afa9cfc5d7130d2d3a51d565d73d3219a19#diff-72bacfcd24442cd873811184909bea9cR326) and  [327](https://github.com/r-glennie/CTMCdive/commit/dae50afa9cfc5d7130d2d3a51d565d73d3219a19#diff-72bacfcd24442cd873811184909bea9cR327). The calculation for the index yielded 0 in some cases (`floor(object$dat$dive[i] / dt)==0` when `object$dat$dive[i]` < `dt`). Hence the fix to grab at worst the first element.

Does that seem reasonable (I don't quite follow the logical of this calculation, but might not need to...)

**Comment by r-glennie** [comment]
Yep.
