### ISSUE TITLE
make formulae more general

### ISSUE THREAD

**Issue by dill** [r-glennie/CTMCdive#2]
Currently syntax to specify the formulae is:

```r
# setup model 
forms <- list(surface ~ 1, 
              dive ~ 1)

# fit model 
mod <- FitCTMCdive(forms, dat, model = "sd", print = TRUE)
```

where `model` takes the values: `"s"`, `"d"`, `"sd"`/`"ds"`, or `"iid"`.

Would like to have something more like:

```r
# setup model 
forms <- list(surface ~ s(time, bs="ts", k=10), 
              dive ~ 1)

# fit model 
mod <- FitCTMCdive(forms, dat, print = TRUE)
```

**Comment by dill** [comment]
87d3e01 implements this.

Remaning is to include more fixed effects.

**Comment by dill** [comment]
@r-glennie could you send me some example data that have fixed effects beyond the intercept?

**Comment by r-glennie** [comment]
Sent to you.
